setup = """
CREATE TABLE numbers AS
    WITH RECURSIVE generate_series(value) AS (
        SELECT 1
        UNION ALL
        SELECT value+1 FROM generate_series
        WHERE value+1<=1000
    )
    SELECT value FROM generate_series
;
"""
query = "SELECT value FROM numbers"
repeat = 1000
